[package]
name = "calculator_rs"
version = "0.2.1"
edition = "2021"

# [[test]]
# name = "e2e_tests"
# harness = false

[dev-dependencies]
cucumber = { version = "0.21.1", features = ["macros"] }
tokio = { version = "1.42.0", features = ["full", "macros", "rt-multi-thread"] }
