name: CI (Linux)

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Update toolchain
        run: rustup update --no-self-update stable && rustup default stable

      - name: Install dependencies
        run: cargo fetch

      - name: Run tests
        run: cargo test
