name: CI (Windows)

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-2022
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: taiki-e/install-action@nextest

      - name: Install dependencies
        run: cargo fetch

      - name: Run tests
        run: |
          cargo llvm-cov nextest --profile ci
          cargo llvm-cov report --lcov --output-path lcov.info

      - name: Test Results Comment
        uses: EnricoMi/publish-unit-test-result-action/windows@v2
        id: windows-test-results
        if: always()
        with:
          check_name: Windows Test Results
          files: |
            target/nextest/ci/junit.xml

      - uses: actions/upload-artifact@v4
        with:
          name: windows-code-coverage-report
          path: lcov.info
  
  coverage-report:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-code-coverage-report
          path: .

      - name: Run sed
        run: |
          sed -i '' \
            -e '/^SF:/s|D:\\a|/home/runner/work|g' \
            -e '/^SF:/s|\\|/|g' \
            lcov.info

      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1

      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v3
        with:
          title-prefix: Woindows-
          coverage-files: lcov.info
          artifact-name: windows-code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true
  