name: fmt

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update toolchain
        run: rustup update --no-self-update stable && rustup default stable
      - name: Check
        run: cargo fmt --all -- --check